export const mockReports = [
  {
    id: 1,
    internshipTitle: "Frontend Developer Intern",
    companyOrgName: "TechVision",
    introduction: "During my internship at TechVision, I had the opportunity to work with cutting-edge web technologies and contribute to real-world projects.",
    companyDesc: "TechVision is a leading software development company specializing in web applications and digital solutions.",
    tasks: "Developed responsive UI components, implemented new features using React, collaborated in agile team environment",
    evaluation: "The internship provided valuable hands-on experience in modern web development practices and team collaboration.",
    conclusion: "This internship has significantly enhanced my technical skills and professional growth in web development.",
    satisfaction: "Very satisfied",
    recommendation: "Yes",    references: "Senior Developer: John Smith, Project Manager: Sarah Johnson",
    appendencies: "Project documentation, Code samples",
    status: "Accepted",
    major: "CSEN",
    selectedCourses: ["Software Engineering", "Databses I", "Introduction to Communication Networks"]
  },
  {
    id: 2,
    internshipTitle: "UI/UX Design Intern",
    companyOrgName: "CreativeMinds",
    introduction: "My internship at CreativeMinds focused on user experience design and interface development for mobile applications.",
    companyDesc: "CreativeMinds is a design agency known for creating innovative digital experiences.",
    tasks: "Created wireframes, conducted user research, designed UI components, participated in design reviews",
    evaluation: "Gained extensive experience in the complete design process and user-centered design principles.",
    conclusion: "The internship has helped me develop a strong foundation in UI/UX design practices.",
    satisfaction: "Somehow satisfied",
    recommendation: "Maybe",    references: "Design Lead: Emily Chen, Creative Director: Michael Brown",
    appendencies: "Design portfolio, User research findings",
    status: "Flagged",
    major: "DMET",
    selectedCourses: ["Computer Graphics", "Web Technologies and Usability", "Visualization and Animation"]
  },
  {
    id: 3,
    internshipTitle: "Software Engineering Intern",
    companyOrgName: "InnovateAI",
    introduction: "At InnovateAI, I worked on developing and optimizing machine learning models for real-world applications.",
    companyDesc: "InnovateAI is a cutting-edge AI research company focusing on developing practical AI solutions for businesses.",
    tasks: "Implemented ML algorithms, optimized model performance, developed testing frameworks, documented API usage",
    evaluation: "The internship provided deep insights into practical machine learning and software engineering best practices.",
    conclusion: "This experience has strengthened my understanding of AI applications in industry.",
    satisfaction: "Very satisfied",
    recommendation: "Yes",    references: "AI Team Lead: Dr. Alex Kim, Senior Engineer: Michael Chen",
    appendencies: "Project reports, Model documentation",
    status: "Pending",
    major: "CSEN",
    selectedCourses: ["Data Structures and Algorithms", "Software Engineering", "Databses II"]
  },
  {
    id: 4,
    internshipTitle: "Digital Media Producer",
    companyOrgName: "MediaSphere",
    introduction: "During my time at MediaSphere, I contributed to various multimedia projects and digital content creation.",
    companyDesc: "MediaSphere is a leading digital media company specializing in interactive content and visual storytelling.",
    tasks: "Created interactive media, designed user interfaces, developed animation sequences, collaborated on content strategy",
    evaluation: "Gained comprehensive experience in digital media production and interactive design.",
    conclusion: "The internship has provided valuable industry exposure and practical skills in media engineering.",
    satisfaction: "Somehow satisfied",
    recommendation: "Maybe",    references: "Creative Director: Sarah White, Technical Lead: James Rodriguez",
    appendencies: "Portfolio of work, Project presentations",
    status: "Rejected",
    major: "DMET",
    selectedCourses: ["Computer Graphics", "Introduction to Media Engineering", "Web Technologies and Usability"]
  }
];
